name: Deploy back-end
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(gradle -q printVersionName)"

      - name: Build application
        run: gradle build

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        env:
          VERSION_LABEL: ArchiTradme-${{ github.run_id }}
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ArchiTradme
          environment_name: Architradme-env
          version_label: ${{ env.VERSION_LABEL }}-${{ steps.version.outputs.version }}
          region: eu-west-3
          deployment_package: build/libs/ArchiTradme-${{ steps.version.outputs.version }}.jar